### ISSUE TITLE
Allow for excluded tag when using tag-regex

### ISSUE THREAD

**Issue by FlippievanDyk** [vlaurin/action-ghcr-prune#9]
I want to use this to remove images created during pull requests, however, sometimes some of the images may receive additional tags, if a team member needs to use a specific version for some tests. 

If one could add an exclusion either regex, or fixed tag, then one could instead of saying keep latest say exclude: 'stable' for example.

I've not looked at the code at all, so I'm not sure what this would take, but If my thinking is right, a list is generated of images with tags to be removed. Then one could simply apply a second filter excluding those that need to be excluded.

Alternatively, and I haven't tested this, will an image with multiple tags be pruned by default? If that approach were followed, the matching tags could be removed, and then all untagged could be removed.

**Comment by vlaurin** [comment]
Hi @FlippievanDyk, thank you for raising that issue.

> If one could add an exclusion either regex, or fixed tag, then one could instead of saying keep latest say exclude: 'stable' for example.
>
>I've not looked at the code at all, so I'm not sure what this would take, but If my thinking is right, a list is generated of images with tags to be removed. Then one could simply apply a second filter excluding those that need to be excluded.

I can see the benefit of this feature. Just to make sure I understood, could you please confirm whether the following example would cover your needs?

```yml
steps:
  - name: Prune
    uses: vlaurin/action-ghcr-prune@main
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      organization: your-org
      container: your-container
      tag-regex: ^pr-
      keep-tags: |
        pr-demo
        pr-test
        stable
```

So any version which has at least one of `pr-demo`, `pr-test` or `stable` would be kept regardless of whether another tag matches `tag-regex`. This means `keep-tags` would always take precedence over `tag-regex`

> Alternatively, and I haven't tested this, will an image with multiple tags be pruned by default? If that approach were followed, the matching tags could be removed, and then all untagged could be removed.

The way `tag-regex` currently works is that it will prune any version which has at least 1 tag matching the regex. As long as this is true, the version will be deleted regardless of other tags on that version.

I think removing tags without deleting the version is beyond the scope of this action. I'm concerned it would make the behaviour of the action too complex while also breaking the action's idempotence.

That being said, I could imagine a fork of this action (eg. `action-ghcr-untag`) which would exclusively remove tags instead of deleting version. This would give users the ability to combine both actions in their workflows while respecting separation of responsibilities and avoiding the complexity overhead in this action.
